# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61221b9a6741b2518e1f8554aee402f6d937532f588e1bb91f2963e6564678f288041d05500dd2230c5871f8256cf1ad40214dd0eb618a2b5ce8dd6e9934609c

test:
  secret_key_base: 7fe67fcc11eaccdc0f59fab9ddffb7517167cdea58ea8ccf0696c51b1858fe00bf30c8e1033cc0d0a22381e3e5dc058c62983765ea356f0ee9c90f6b3f594cc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
